name: Uboot Ubuntu CI Build

on:
  #对应的是 UTC 时间，需要转换，0 代表北京时间8点，每个月1日/15日12点编译一次
  #关闭则手动编译
  workflow_dispatch:
    inputs:
      soc:
        required: true
        description: SOC/CPU Model
        type: string
        default: mt7981
      board:
        required: true
        description: Router Model Name
        type: string
        default: cmcc_rax3000m
      multi-layout:
        required: true
        description: Enable Multiple Flash Layout Support
        type: choice
        default: '0'
        options:
          - '0'
          - '1'
      runs-on:
        required: true
        description: Runs on...
        type: choice
        default: ubuntu-latest
        options:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-latest

jobs:
  ubuntu-build:
    name: Build U-Boot-798x
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: write
      actions: write    
    steps:
      - uses: actions/checkout@v4
      - name: Get build dept.
        run: |
          sudo apt update
          sudo apt install gcc-aarch64-linux-gnu build-essential flex bison libssl-dev device-tree-compiler
      - name: Build it
        run: |
          ./build.sh
        env:
          SOC: ${{ inputs.soc }}
          BOARD: ${{ inputs.board }}
          MULTI_LAYOUT: ${{ inputs.multi-layout }}
      - uses: actions/upload-artifact@v4
        with:
          name: Uboot - ${{ inputs.board }} (${{ inputs.soc }})
          path: output/*.bin
