name: Build BL2 and FIP

on:
  push:

jobs:
  generate_list:
    name: Generate build list
    runs-on: ubuntu-latest
    outputs:
      list: ${{ steps.list.outputs.list }}

    steps:
      - name: Checkout source tree
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Generate build list
        id: list
        run: |
          JSON_LIST="{\"runner\": [\"ubuntu-latest\"],\"list\": [mt7981_newland_nl-wr8103_multi_layout_defconfig]}"
          echo "$JSON_LIST" | jq .
          echo "list=$JSON_LIST" >> "$GITHUB_OUTPUT"

  build:
    name: Build ${{ matrix.list }}
    needs: generate_list
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix: ${{ fromJson(needs.generate_list.outputs.list) }}
      fail-fast: false
      max-parallel: 15

    steps:
      - name: Install dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get install gcc-aarch64-linux-gnu build-essential flex bison libssl-dev device-tree-compiler

      - name: Checkout source tree
        uses: actions/checkout@v4

      - name: Build BL2 and FIP
        env:
          CONFIG: ${{ matrix.list }}
        run: |
          export SOC="${CONFIG%%_*}"
          BOARD=${CONFIG#*_}
          export BOARD=${BOARD%_*}
          mkdir -p output
          ./build.sh 2>&1 | tee output/build.log
          echo "ARTIFACT_NAME=$SOC-$BOARD" >> "$GITHUB_ENV"

      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: output/*
